# InvBlock Config
# #
# check-updates: Whether InvBlock should notify you about newer versions
# #
# inv-mode: One of:
#       - whitelist - blocking only occurs in the given worlds (default)
#       - blacklist - blocking occurs in all worlds except those given
# #
# inv-worlds: A list of either whitelisted or blacklisted worlds for inventory use/clearing
# #
# spawn-mode: One of:
#       - whitelist - respawning only occurs in the given worlds (default)
#       - blacklist - respawning occurs in all worlds except those given
# #
# spawn-worlds: A list of either whitelisted or blacklisted worlds for respawning
# #
check-updates: true
inv-mode: whitelist
inv-worlds: [ 'pvp', 'world_no_inv' ]
spawn-mode: whitelist
spawn-worlds: [ 'pvp', 'world_respawn_on_relog' ]
configVersionDoNotTouch: 2
